# Generated by Django 2.0.2 on 2018-02-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_poem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='poem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='last_updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
