# Generated by Django 2.0.2 on 2018-02-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180227_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poem',
            old_name='poem_content',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='poem_author',
        ),
        migrations.RemoveField(
            model_name='poem',
            name='poem_title',
        ),
        migrations.AddField(
            model_name='poem',
            name='author',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='poem',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
